### ISSUE TITLE
Separate content from styling in the cartodbLayers.js 

### ISSUE THREAD

**Issue by nmanaud** [nmanaud/whereonmars#6]
We should be able to style each (CartoDB) layer in a separate (Carto)CSS file.

For example:
```javascript
  el.geoNoOkContraint = layer.createSubLayer({
          sql: "SELECT * FROM geological_age_not_ok",
          cartocss: "#geological_age_not_ok{ polygon-fill: #000000;polygon-opacity: 1;line-color: #FFF;line-width: 0.5;line-opacity: 1;}"  
      });
```
```css
#geological_age_not_ok{
  polygon-fill: #000000;
  polygon-opacity: 0.6;
  line-color: #FFF;
  line-width: 0;
  line-opacity: 1;
}
```
